mysql:
  image: mysql:8.0
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=cisapify
  volumes:
    - /tmp/opt/cisapify/mysql_data:/var/lib/mysql # once system restarts the data will be removed